name: jasen
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - any2fasta=0.4.2=2
  - ariba=2.14.5=py37hfa133b6_1
  - bcftools=1.5=3
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - binutils_impl_linux-64=2.35.1=h17ad2fc_0
  - binutils_linux-64=2.35=hc3fd857_29
  - biopython=1.78=py37h8f50634_1
  - blast=2.9.0=pl526h3066fca_4
  - bowtie2=2.4.2=py37h8270d21_1
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - bwa=0.7.17=hed695b0_7
  - bwidget=1.9.14=ha770c72_0
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2020.11.8=ha878542_0
  - cairo=1.14.12=h80bd089_1005
  - cd-hit=4.8.1=h8b12597_3
  - certifi=2020.11.8=py37h89c1867_0
  - cffi=1.14.3=py37h00ebd2e_1
  - chardet=3.0.4=py37he5f6b98_1008
  - chewbbaca=2.5.6=py_0
  - circos=0.69.8=0
  - clustalw=2.1=hc9558a2_5
  - cni=0.8.0=hc0beb16_0
  - cni-plugins=0.8.7=ha8f183a_1
  - cryptography=3.2.1=py37hc72a4ac_0
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py_2
  - dendropy=4.5.1=pyh3252c3a_0
  - entrez-direct=13.9=pl526h375a9b1_0
  - expat=2.2.9=he1b5a44_2
  - fastqc=0.11.9=0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fontconfig=2.13.1=he4413a7_1000
  - freebayes=1.3.2=py37h26878c9_2
  - freetype=2.10.4=h7ca028e_0
  - gatk4=4.1.9.0=py39_0
  - gcc_impl_linux-64=7.5.0=hda68d29_13
  - gcc_linux-64=7.5.0=he2a3fca_29
  - gettext=0.19.8.1=hf34092f_1004
  - gfortran_impl_linux-64=7.5.0=hfca37b7_17
  - gfortran_linux-64=7.5.0=ha081f1e_29
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.56.2=had28632_1001
  - glimmerhmm=3.0.4=pl526hf484d3e_3
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.38.0=hcf1ce16_1009
  - gsl=2.6=hf94e986_0
  - gxx_impl_linux-64=7.5.0=h64c220c_13
  - gxx_linux-64=7.5.0=h547f3ba_29
  - harfbuzz=1.9.0=he243708_1001
  - htslib=1.10.2=h78d89cc_0
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h36c2ea0_0
  - jq=1.6=h14c3975_1000
  - k8=0.2.5=he513fc3_0
  - keepalive=0.5=py37hc8dfbb8_4
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.3.1=py37hc928c03_0
  - kraken2=2.1.1=pl526hc9558a2_0
  - krb5=1.16.4=h2fd8d38_0
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.35.1=hed1e6ac_0
  - libarchive=3.3.3=hddc7a2b_1008
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libcurl=7.68.0=hda55be3_0
  - libdb=6.1.26=0
  - libdeflate=1.3=h516909a_0
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgd=2.2.5=h0d07dcb_1005
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.0=h516909a_0
  - liblapack=3.9.0=2_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libseccomp=2.4.4=h36c2ea0_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h58526e2_1007
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - libxslt=1.1.32=hae48121_1003
  - llvm-meta=7.0.0=0
  - lz4-c=1.9.2=he1b5a44_3
  - lzo=2.10=h516909a_1000
  - mafft=7.471=h516909a_0
  - make=4.3=hd18ef5c_1
  - matplotlib-base=3.3.3=py37h4f6019d_0
  - minimap2=2.17=hed695b0_3
  - mlst=2.19.0=0
  - mummer=3.23=pl526he1b5a44_11
  - ncurses=6.2=h58526e2_3
  - numpy=1.19.4=py37h7e9df27_1
  - olefile=0.46=pyh9f0ad1d_1
  - oniguruma=6.9.3=h516909a_0
  - openjdk=8.0.265=h516909a_0
  - openmp=7.0.0=h2d50403_0
  - openssl=1.1.1h=h516909a_0
  - paml=4.9=h516909a_5
  - pandas=1.1.4=py37h10a2094_0
  - pango=1.40.14=hf0c64fd_1003
  - parallel=20160622=1
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h36c2ea0_1008
  - perl-aceperl=1.92=pl526_2
  - perl-algorithm-diff=1.1903=pl526_2
  - perl-algorithm-munkres=0.08=pl526_1
  - perl-apache-test=1.40=pl526_1
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-appconfig=1.71=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-array-compare=3.0.1=pl526_1
  - perl-autoloader=5.74=pl526_2
  - perl-base=2.23=pl526_1
  - perl-bio-asn1-entrezgene=1.73=pl526_1
  - perl-bio-coordinate=1.007001=pl526_1
  - perl-bio-featureio=1.6.905=pl526_2
  - perl-bio-phylo=0.58=pl526_2
  - perl-bio-samtools=1.43=pl526h1341992_1
  - perl-bio-tools-phylo-paml=1.7.3=pl526_1
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl526_1
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl526_2
  - perl-bioperl=1.7.2=pl526_11
  - perl-bioperl-core=1.007002=pl526_2
  - perl-bioperl-run=1.007002=pl526_4
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-cache-cache=1.08=pl526_0
  - perl-capture-tiny=0.48=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-cgi=4.44=pl526h14c3975_1
  - perl-class-data-inheritable=0.08=pl526_1
  - perl-class-inspector=1.34=pl526_0
  - perl-class-load=0.25=pl526_0
  - perl-class-load-xs=0.10=pl526h6bb024c_2
  - perl-class-method-modifiers=2.12=pl526_0
  - perl-clone=0.42=pl526h516909a_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-config-general=2.63=pl526_0
  - perl-constant=1.33=pl526_1
  - perl-convert-binary-c=0.78=pl526h6bb024c_3
  - perl-convert-binhex=1.125=pl526_1
  - perl-crypt-rc4=2.02=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-data-optlist=0.110=pl526_2
  - perl-data-stag=0.14=pl526_1
  - perl-date-format=2.30=pl526_2
  - perl-db-file=1.852=pl526h14c3975_0
  - perl-dbd-sqlite=1.64=pl526h516909a_0
  - perl-dbi=1.642=pl526_0
  - perl-devel-globaldestruction=0.14=pl526_0
  - perl-devel-overloadinfo=0.005=pl526_0
  - perl-devel-stacktrace=2.04=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-digest-sha1=2.13=pl526h6bb024c_1
  - perl-dist-checkconflicts=0.11=pl526_2
  - perl-dynaloader=1.25=pl526_1
  - perl-email-date-format=1.005=pl526_2
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-error=0.17027=pl526_1
  - perl-eval-closure=0.14=pl526h6bb024c_4
  - perl-exception-class=1.44=pl526_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-slurp-tiny=0.004=pl526_1
  - perl-file-sort=1.01=pl526_2
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-font-afm=1.20=pl526_2
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526he860b03_0
  - perl-getopt-long=2.50=pl526_1
  - perl-graph=0.9704=pl526_1
  - perl-graphviz=2.24=pl526h734ff71_0
  - perl-html-element-extended=1.18=pl526_1
  - perl-html-entities-numbered=0.04=pl526_1
  - perl-html-formatter=2.16=pl526_0
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tableextract=2.13=pl526_2
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tidy=1.60=pl526_0
  - perl-html-tree=5.07=pl526_1
  - perl-html-treebuilder-xpath=0.14=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-image-info=1.38=pl526_1
  - perl-image-size=3.300=pl526_2
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-sessiondata=1.03=pl526_1
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-string=1.08=pl526_3
  - perl-io-stringy=2.111=pl526_1
  - perl-io-tty=1.12=pl526_1
  - perl-io-zlib=1.10=pl526_2
  - perl-ipc-run=20180523.0=pl526_0
  - perl-ipc-sharelite=0.17=pl526h6bb024c_1
  - perl-jcode=2.07=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-lib=0.63=pl526_1
  - perl-libwww-perl=6.39=pl526_0
  - perl-libxml-perl=0.08=pl526_2
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-lwp-simple=6.15=pl526h470a237_4
  - perl-mailtools=2.21=pl526_0
  - perl-math-bezier=0.01=pl526_1
  - perl-math-cdf=0.1=pl526h14c3975_5
  - perl-math-derivative=1.01=pl526_0
  - perl-math-random=0.72=pl526h14c3975_2
  - perl-math-round=0.07=pl526_1
  - perl-math-spline=0.02=pl526_2
  - perl-math-vecstat=0.08=pl526_1
  - perl-mime-base64=3.15=pl526_1
  - perl-mime-lite=3.030=pl526_1
  - perl-mime-tools=5.508=pl526_1
  - perl-mime-types=2.17=pl526_0
  - perl-mldbm=2.05=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_1
  - perl-module-runtime-conflicts=0.003=pl526_0
  - perl-moo=2.003004=pl526_0
  - perl-moose=2.2011=pl526hf484d3e_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-mro-compat=0.13=pl526_0
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-number-format=1.75=pl526_3
  - perl-ole-storage_lite=0.19=pl526_3
  - perl-package-deprecationmanager=0.17=pl526_0
  - perl-package-stash=0.38=pl526hf484d3e_1
  - perl-package-stash-xs=0.28=pl526hf484d3e_1
  - perl-params-util=1.07=pl526h6bb024c_4
  - perl-params-validate=1.29=pl526h14c3975_1
  - perl-parent=0.236=pl526_1
  - perl-parse-recdescent=1.967015=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-pdf-api2=2.035=pl526_0
  - perl-pod-escapes=1.07=pl526_1
  - perl-pod-usage=1.69=pl526_1
  - perl-postscript=0.06=pl526_2
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-role-tiny=2.000008=pl526_0
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-set-intspan=1.19=pl526_1
  - perl-set-scalar=1.29=pl526_2
  - perl-soap-lite=1.19=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-sort-naturally=1.03=pl526_2
  - perl-spreadsheet-parseexcel=0.65=pl526_2
  - perl-spreadsheet-writeexcel=2.40=pl526_2
  - perl-statistics-basic=1.6611=pl526_2
  - perl-statistics-descriptive=3.0702=pl526_0
  - perl-storable=3.15=pl526h14c3975_0
  - perl-sub-exporter=0.987=pl526_2
  - perl-sub-exporter-progressive=0.001013=pl526_0
  - perl-sub-identify=0.14=pl526h14c3975_0
  - perl-sub-install=0.928=pl526_2
  - perl-sub-name=0.21=pl526_1
  - perl-sub-quote=2.006003=pl526_1
  - perl-sub-uplevel=0.2800=pl526h14c3975_2
  - perl-svg=2.84=pl526_0
  - perl-svg-graph=0.02=pl526_3
  - perl-task-weaken=1.06=pl526_0
  - perl-template-toolkit=2.26=pl526_1
  - perl-test=1.26=pl526_1
  - perl-test-deep=1.128=pl526_1
  - perl-test-differences=0.67=pl526_0
  - perl-test-exception=0.43=pl526_2
  - perl-test-harness=3.42=pl526_0
  - perl-test-leaktrace=0.16=pl526h14c3975_2
  - perl-test-most=0.35=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-test-warn=0.36=pl526_1
  - perl-text-diff=1.45=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-threaded=5.26.0=0
  - perl-tie-ixhash=1.23=pl526_2
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-time-local=1.28=pl526_1
  - perl-timedate=2.30=pl526_1
  - perl-tree-dag_node=1.31=pl526_0
  - perl-try-tiny=0.30=pl526_1
  - perl-type-tiny=1.004004=pl526_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-unicode-map=0.112=pl526h6bb024c_3
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-dom=1.46=pl526_0
  - perl-xml-dom-xpath=0.14=pl526_1
  - perl-xml-filter-buffertext=1.01=pl526_2
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-libxslt=1.94=pl526_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44=pl526h4e0c4b3_7
  - perl-xml-regexp=0.04=pl526_2
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-sax-writer=0.57=pl526_0
  - perl-xml-simple=2.25=pl526_1
  - perl-xml-twig=3.52=pl526_2
  - perl-xml-writer=0.625=pl526_2
  - perl-xml-xpath=1.44=pl526_0
  - perl-xml-xpathengine=0.14=pl526_2
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - picard=2.23.8=0
  - pillow=8.0.1=py37h63a5d19_0
  - pip=20.2.4=py_0
  - pixman=0.34.0=h14c3975_1003
  - plotly=4.12.0=pyh9f0ad1d_0
  - popt=1.16=1
  - prodigal=2.6.3=h516909a_2
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfastaq=3.17.0=py_2
  - pymummer=0.10.3=py_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysam=0.15.3=py37hbcae180_3
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.1=h381d211_1003
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.4=pyhd8ed1ab_0
  - quast=5.0.2=py37pl526hb5aa323_2
  - r-base=3.5.1=he45234b_1005
  - readline=7.0=hf8c457e_1001
  - requests=2.25.0=pyhd3deb0d_0
  - retrying=1.3.3=py_2
  - rsync=3.1.3=hed695b0_1002
  - samtools=1.10=h2e538c0_3
  - scipy=1.5.3=py37h8911b10_0
  - setuptools=49.6.0=py37he5f6b98_2
  - simplejson=3.17.2=py37h8f50634_1
  - singularity=3.6.3=hf9e9d37_0
  - six=1.15.0=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - spades=3.14.1=h2d02072_0
  - sparqlwrapper=1.8.5=py37hc8dfbb8_1004
  - sqlite=3.28.0=h8b20d00_0
  - squashfs-tools=4.3=h41c4fab_1004
  - sysroot_linux-64=2.12=h77966d4_13
  - t_coffee=11.0.8=py37hea885bf_8
  - tar=1.32=hd4ba37b_0
  - tbb=2020.2=hc9558a2_0
  - tidyp=1.04=h516909a_2
  - tk=8.6.10=hed695b0_1
  - tktable=2.10=hb7b940f_3
  - tornado=6.1=py37h4abf009_0
  - trimmomatic=0.39=1
  - urllib3=1.25.11=py_0
  - vcftools=0.1.16=he513fc3_4
  - wget=1.20.1=h22169c7_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - click==7.1.2
    - coloredlogs==14.0
    - colormath==3.0.0
    - decorator==4.4.2
    - future==0.18.2
    - humanfriendly==8.2
    - importlib-metadata==2.0.0
    - jinja2==2.11.2
    - lzstring==1.0.4
    - markdown==3.3.3
    - markupsafe==1.1.1
    - multiqc==1.9
    - networkx==2.5
    - pyyaml==5.3.1
    - spectra==0.0.11
    - zipp==3.4.0
